#!/usr/bin/env python3
"""
check_data.py — Pre-flight data check for causal-graph-engine.

Verifies that all required data files are present before running the pipeline.
Run this after completing the data setup steps in README.md.

Usage:
    python scripts/check_data.py           # check all diseases
    python scripts/check_data.py --disease CAD
    python scripts/check_data.py --disease RA
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"


def check(label: str, path: Path) -> bool:
    ok = path.exists() and path.stat().st_size > 1000
    status = "OK" if ok else "MISSING"
    print(f"  [{status}]  {label}")
    if not ok:
        print(f"           → {path}")
    return ok


def run(diseases: list[str]) -> bool:
    all_ok = True
    print("\n── Static reference data ──────────────────────────────")
    for name, fname in [
        ("gnomAD constraint (pLI)", "data/static/gnomad_constraint.tsv"),
        ("HGNC gene table",         "data/static/hgnc_complete.tsv"),
        ("Reactome pathways",       "data/static/reactome_ensembl2pathways.tsv"),
        ("shet posteriors",         "data/genebays/shet_posteriors.tsv"),
    ]:
        all_ok &= check(name, ROOT / fname)

    for disease in diseases:
        disease_up = disease.upper()
        print(f"\n── {disease_up} ────────────────────────────────────────────")

        # CellxGENE h5ad
        cell_map = {"CAD": "cardiac_endothelial_cell", "RA": "CD4_positive_alpha_beta_T_cell"}
        cell_type = cell_map.get(disease_up, "")
        h5ad = DATA / "cellxgene" / disease_up / f"{disease_up}_{cell_type}.h5ad"
        all_ok &= check(f"CellxGENE h5ad ({cell_type})", h5ad)

        # Perturb-seq
        if disease_up == "CAD":
            all_ok &= check(
                "Perturb-seq signatures (Schnitzler GSE210681)",
                DATA / "perturbseq" / "schnitzler_cad_vascular" / "signatures.json.gz",
            )
        elif disease_up == "RA":
            czi_dir = DATA / "perturbseq" / "czi_2025_cd4t_perturb"
            h5ads = list(czi_dir.glob("*.h5ad")) if czi_dir.exists() else []
            ok = bool(h5ads)
            print(f"  [{'OK' if ok else 'MISSING'}]  Perturb-seq h5ad (CZI CD4+ T, {len(h5ads)} file(s) found)")
            if not ok:
                print(f"           → {czi_dir}/*.h5ad")
            all_ok &= ok

        # S-LDSC sumstats
        ldsc_map = {"CAD": "Phe_414.EUR.gwama.sumstats.txt.gz",
                    "RA":  "Phe_714.EUR.gwama.sumstats.txt.gz"}
        sumstat = ldsc_map.get(disease_up, "")
        if sumstat:
            all_ok &= check(f"S-LDSC sumstats ({sumstat})", DATA / "ldsc" / "sumstats" / sumstat)

        # S-LDSC pre-computed τ results (generated by runner.py)
        tau_file = DATA / "ldsc" / "results" / f"{disease_up}_program_taus.json"
        ok = tau_file.exists() and tau_file.stat().st_size > 100
        status = "OK" if ok else "MISSING"
        print(f"  [{status}]  S-LDSC τ results ({disease_up}_program_taus.json)")
        if not ok:
            print(f"           → {tau_file}")
            print(f"           → Run: python -m pipelines.ldsc.runner run {disease_up}")
        all_ok &= ok

    print()
    if all_ok:
        print("All checks passed. Pipeline is ready to run.")
    else:
        print("Some required files are missing. See README.md § Data setup.")
        print("Re-run after completing the missing steps.")
    return all_ok


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--disease", nargs="+", default=["CAD", "RA"],
                        help="Diseases to check (default: CAD RA)")
    args = parser.parse_args()
    ok = run([d.upper() for d in args.disease])
    sys.exit(0 if ok else 1)
